"""Add ...

Revision ID: 8ea5842bd6b9
Revises: 
Create Date: 2025-10-12 17:25:04.773445

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8ea5842bd6b9'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_uuid', sa.UUID(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('salt', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('user_uuid'),
    sa.UniqueConstraint('username')
    )
    op.create_index('idx_email', 'users', ['email'], unique=False)
    op.create_index('idx_user_uuid', 'users', ['user_uuid'], unique=False)
    op.create_index('idx_username', 'users', ['username'], unique=False)
    op.create_table('posts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('post_uuid', sa.UUID(), nullable=False),
    sa.Column('post_text', sa.Text(), nullable=False),
    sa.Column('post_image', sa.Text(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('post_uuid')
    )
    op.create_index('idx_post_created_at', 'posts', ['created_at'], unique=False)
    op.create_index('idx_post_user_id', 'posts', ['user_id'], unique=False)
    op.create_index('idx_post_uuid', 'posts', ['post_uuid'], unique=False)
    op.create_table('comments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('comment_uuid', sa.UUID(), nullable=False),
    sa.Column('comment_text', sa.Text(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('parent_comment_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['parent_comment_id'], ['comments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('comment_uuid')
    )
    op.create_index('idx_comment_parent_comment_id', 'comments', ['parent_comment_id'], unique=False)
    op.create_index('idx_comment_post_id', 'comments', ['post_id'], unique=False)
    op.create_index('idx_comment_user_id', 'comments', ['user_id'], unique=False)
    op.create_index('idx_comment_uuid', 'comments', ['comment_uuid'], unique=False)
    op.create_table('likes',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'post_id')
    )
    op.create_index('idx_like_post_id', 'likes', ['post_id'], unique=False)
    op.create_index('idx_like_user_id', 'likes', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_like_user_id', table_name='likes')
    op.drop_index('idx_like_post_id', table_name='likes')
    op.drop_table('likes')
    op.drop_index('idx_comment_uuid', table_name='comments')
    op.drop_index('idx_comment_user_id', table_name='comments')
    op.drop_index('idx_comment_post_id', table_name='comments')
    op.drop_index('idx_comment_parent_comment_id', table_name='comments')
    op.drop_table('comments')
    op.drop_index('idx_post_uuid', table_name='posts')
    op.drop_index('idx_post_user_id', table_name='posts')
    op.drop_index('idx_post_created_at', table_name='posts')
    op.drop_table('posts')
    op.drop_index('idx_username', table_name='users')
    op.drop_index('idx_user_uuid', table_name='users')
    op.drop_index('idx_email', table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
