"""Add ...

Revision ID: 670bbbb41e44
Revises: fa3dcfc2b599
Create Date: 2025-10-14 10:32:06.863895

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '670bbbb41e44'
down_revision: Union[str, None] = 'fa3dcfc2b599'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('follows',
    sa.Column('follower_id', sa.Integer(), nullable=False),
    sa.Column('following_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['follower_id'], ['users.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['following_id'], ['users.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('follower_id', 'following_id')
    )
    op.create_index('idx_follower_id', 'follows', ['follower_id'], unique=False)
    op.create_index('idx_following_id', 'follows', ['following_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_following_id', table_name='follows')
    op.drop_index('idx_follower_id', table_name='follows')
    op.drop_table('follows')
    # ### end Alembic commands ###
