"""Add ...

Revision ID: d733a1eb520a
Revises: 670bbbb41e44
Create Date: 2025-10-17 07:12:03.568921

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd733a1eb520a'
down_revision: Union[str, None] = '670bbbb41e44'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('comments', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('idx_comment_parent_comment_id'), table_name='comments')
    op.create_index('idx_comment_parent_id', 'comments', ['parent_comment_id'], unique=False)
    op.create_index('idx_comment_post_created', 'comments', ['post_id', 'created_at'], unique=False)
    op.drop_index(op.f('idx_follower_id'), table_name='follows')
    op.drop_index(op.f('idx_following_id'), table_name='follows')
    op.create_index('idx_follow_created_at', 'follows', ['created_at'], unique=False)
    op.create_index('idx_follow_follower_id', 'follows', ['follower_id'], unique=False)
    op.create_index('idx_follow_following_id', 'follows', ['following_id'], unique=False)
    op.create_index('idx_like_created_at', 'likes', ['created_at'], unique=False)
    op.add_column('posts', sa.Column('is_published', sa.Boolean(), nullable=False))
    op.alter_column('posts', 'post_image',
               existing_type=sa.TEXT(),
               type_=sa.String(length=500),
               existing_nullable=True)
    op.alter_column('posts', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.create_index('idx_post_user_created', 'posts', ['user_id', 'created_at'], unique=False)
    op.add_column('users', sa.Column('is_active', sa.Boolean(), nullable=False))
    op.add_column('users', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('users', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.drop_index(op.f('idx_email'), table_name='users')
    op.drop_index(op.f('idx_username'), table_name='users')
    op.create_index('idx_user_email', 'users', ['email'], unique=False)
    op.create_index('idx_user_username', 'users', ['username'], unique=False)
    op.drop_column('users', 'salt')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('salt', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.drop_index('idx_user_username', table_name='users')
    op.drop_index('idx_user_email', table_name='users')
    op.create_index(op.f('idx_username'), 'users', ['username'], unique=False)
    op.create_index(op.f('idx_email'), 'users', ['email'], unique=False)
    op.drop_column('users', 'updated_at')
    op.drop_column('users', 'created_at')
    op.drop_column('users', 'is_active')
    op.drop_index('idx_post_user_created', table_name='posts')
    op.alter_column('posts', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('posts', 'post_image',
               existing_type=sa.String(length=500),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.drop_column('posts', 'is_published')
    op.drop_index('idx_like_created_at', table_name='likes')
    op.drop_index('idx_follow_following_id', table_name='follows')
    op.drop_index('idx_follow_follower_id', table_name='follows')
    op.drop_index('idx_follow_created_at', table_name='follows')
    op.create_index(op.f('idx_following_id'), 'follows', ['following_id'], unique=False)
    op.create_index(op.f('idx_follower_id'), 'follows', ['follower_id'], unique=False)
    op.drop_index('idx_comment_post_created', table_name='comments')
    op.drop_index('idx_comment_parent_id', table_name='comments')
    op.create_index(op.f('idx_comment_parent_comment_id'), 'comments', ['parent_comment_id'], unique=False)
    op.alter_column('comments', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    # ### end Alembic commands ###
